### ISSUE TITLE
Exported .skn has majorly distorted UVs

### ISSUE THREAD

**Issue by RoyalMaps** [lispascal/lolblender#21]
Regardless if I base the file on an imported file, or if different versions are manually selected, any model with custom UV will be distorted on export.

All normals facing correct way, all faces triangulated.  I am using blender 2.77 and I use Wooxy to preview my models (using the Model viewer/converter in the 'creation' tab).

Using this tool, I am able to export the .skn into an obj. The resulting obj reveals the UV mesh has been scrambled.

I have included the exported .obj file. It showcases the distorted UVs.

[Example_UV_Distortion.zip](https://github.com/lispascal/lolblender/files/674839/Example_UV_Distortion.zip)

**Comment by Crauzer** [comment]
The blender plugin is dead and kinda bad. You should use the newest plugin for Maya 2017. You can find it on mapskins if you do a simple google search

**Comment by lispascal** [comment]
Thanks for waiting.

@RoyalMaps What process are you using for exporting skn to an OBJ? Because of the way you say it, I assume you are importing from .skn and then directly exporting to .obj.

1. Are the UVs distorted in Blender after just importing?
2. Are you doing any manipulation of the model before exporting it?
3. Could you attach the .skn file you were using here?

For Crauzer's comment: I don't disagree. This isn't being updated or worked on regularly (I have stopped playing League, anyway), but I may still try to help the user if he has an issue. Regarding Maya, it's an expensive program, which is why I worked on this plugin for use with the free-to-use Blender.

**Comment by RoyalMaps** [comment]
Sorry for the misunderstanding @lispascal , I just used Wooxy to view and troubleshoot the UV issue. When I say .skn to .obj, that was part of the troubleshooting process.

My problem is when I export to .skn, the resulting .skn file's UVs are messed up.

I am making a custom model and then applying the bones and all the other proper steps
I then export. The resulting .skn file has bad UVs.

**Comment by shoxsz** [comment]
I know that it may be a little too late for this but i'll point just an observation: i have worked with .skn files and .obj with wooxy and have just concluded that when wooxy is converting from .skn to .obj he will invert the uv's y axis, basically wooxy will flip the y vector direction(up/down). To fix this problem just do: uv.y = 1 - uv.y in your shader(or equivalent). I know this because have renderend a model from a .skn file and the same model from a .obj converted with wooxy from the original .skn

**Comment by lispascal** [comment]
Good point @shoxsz ! This tool accounts for UVs being flipped in the y direction when importing from SIU, and also does so when exporting. The way texture coordinates are handled might be different between wooxy and SIU (or perhaps one of the two flips textures vertically to accomodate).

So perhaps @RoyalMaps may be able to work around their issue by changing [Line 375 in their io_scene_lol/lolMesh.py file](https://github.com/lispascal/lolblender/blob/master/io_scene_lol/lolMesh.py#L375) to be
`        vtxUvs[vertex] = [uv[0], uv[1]]` (while keeping the same indentation - 8 spaces)
