### ISSUE TITLE
[EXPORT] No such file or directory

### ISSUE THREAD

**Issue by Fronkln** [lispascal/lolblender#23]
I keep getting this error when i try to export to any of the folders on my computer, it just wont export.
![exbug](https://user-images.githubusercontent.com/17107072/28416824-41de8a28-6d5e-11e7-9f32-f2e6dc1e81a3.png)

**Comment by lispascal** [comment]
Looks like it happens because you've selected "base on imported SKN" on the export screen (see the lower left when you can name the exported .skn file), but didn't specify a file. The fix would be to either specify the name of the SKN in the directory on which you based your skin (for the tool's use for .SKN metadata stuff), or uncheck that box.

Additionally, I found that it seems to cause an error when you try to uncheck that box and export without basing it on an imported skin, which I have fixed with be52cc0

Let me know if that works.

**Comment by Fronkln** [comment]
I have forgotten to write, but yes after this update all my problems were gone.
